import lorrainjs from "../index.js";
console.log(`Toto`);
lorrainjs.initAll();
console.log("Toto");
console.log("Toto !");
console.log("Toto.");
console.log("Tito gros.");
console.log("Tuto dégros");
console.log(`poire`);
console.log(["Toto", "poire"]);
console.log({ fruit: "poire", nom: "Toto" });
console.log(`Patrick aimerais beaucoup manger des pâtes et des oranges`);
