import lorrainjs from "../src/index";
console.log(`Toto`);
lorrainjs.initLog();
lorrainjs.initError();
console.log("Toto");
console.log("Salut. Salut ! Salut. Salut");
console.log("C'est l'heure de changer la couche de Micheline");
console.log("Toto !");
console.log("Toto.");
console.log("Tito gros.");
console.log("Tuto dégros");
console.log(`poire`);
console.log(45);
console.log(`poire`, "baton", true, 1, [2, "chausson"]);
console.log(new Date(2021, 7, 3));
console.log([new Date(2021, 7, 3), "salut"]);
console.log(["Toto", "poire"]);
console.log({ fruit: "poire", nom: "Toto" });
console.log(`Patrick aimerais beaucoup manger des pâtes et des oranges`);
console.error(new Error("donnée non trouvée"));
